POST http://localhost:5120/mentors
Content-Type: application/json

{
    "name": "mentor1",
    "email":"mentor2@gmail.com",
    "username":"mentor134",
    "major":"CSE",
    "university":"kmitn"
}

###

GET http://localhost:5120/mentors