POST http://localhost:5120/project
Content-Type: application/json

{
  "title": "Online Integrated Platform for projects",
  "projectId":"5",
  "field": "CSE",
  "domain": ["Full-Stack", "Machine Learning"],
  "mentorId": "mentor134",
  "universityId": "kmitn",
  "author": ["user22"],
  "abstract": "This is the first project document",
  "docs": "6554a011afa203ac03b1ed5a"
}